import { z } from "zod";

export const questionarioSchema = z.object({
    empregado: z.boolean().nullable(),
    quantos_animais_possui: z.number(),
    motivos_para_adotar: z.string(),
    quem_vai_sustentar_o_animal: z.string(),
    numero_adultos_na_casa: z.number(),
    numero_criancas_na_casa: z.number(),
    idades_criancas: z.array(z.number()).nullable(),
    residencia_tipo: z.string(),
    proprietario_permite_animais: z.boolean(),
    todos_de_acordo_com_adocao: z.boolean(),
    responsavel_pelo_animal: z.string(),
    responsavel_concorda_com_adocao: z.boolean(),
    ha_alergico_ou_pessoas_que_nao_gostam: z.boolean(),
    gasto_mensal_estimado: z.number(),
    valor_disponivel_no_orcamento: z.boolean(),
    tipo_alimentacao: z.string(),
    local_que_o_animal_vai_ficar: z.string(),
    forma_de_permanencia: z.string(),
    forma_de_confinamento: z.string(),
    tera_brinquedos: z.boolean(),
    tera_abrigo: z.boolean(),
    tera_passeios_acompanhado: z.boolean(),
    tera_passeios_sozinho: z.boolean(),
    companhia_outro_animal: z.boolean(),
    companhia_humana_24h: z.boolean(),
    companhia_humana_parcial: z.boolean(),
    sem_companhia_humana: z.boolean(),
    sem_companhia_animal: z.boolean(),
    o_que_faz_em_viagem: z.string(),
    o_que_faz_se_fugir: z.string(),
    o_que_faz_se_nao_puder_criar: z.string(),
    animais_que_ja_criou: z.string(),
    destino_animais_anteriores: z.string(),
    costuma_esterilizar: z.boolean(),
    costuma_vacinar: z.boolean(),
    costuma_vermifugar: z.boolean(),
    veterinario_usual: z.string(),
    forma_de_educar: z.string(),
    envia_fotos_e_videos_do_local: z.boolean(),
    aceita_visitas_e_fotos_do_animal: z.boolean(),
    topa_entrar_grupo_adotantes: z.boolean(),
    concorda_com_taxa_adocao: z.boolean(),
    data_disponivel_para_buscar_animal: z.string()
});
